version: 2.1
jobs:
  build-and-test-common:
    docker:
      - image: cimg/openjdk:17.0
    environment:
      ANDROID_HOME: ~/android-sdk
      PATH: ~/android-sdk/cmdline-tools/latest/bin:$PATH
    steps:
      - checkout
      - run:
          name: Install Android SDK and Tools
          command: |
            mkdir -p $ANDROID_HOME/cmdline-tools/latest
            wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
            unzip commandlinetools-linux-6858069_latest.zip -d $ANDROID_HOME/cmdline-tools/latest
            yes | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-30" "build-tools;30.0.3"
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Run Build
          command: ./gradlew build
      - run:
          name: Run Tests
          command: ./gradlew testDebugUnitTest
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.gradle/caches
workflows:
  build-and-test:
    jobs:
      - build-and-test-common